version: "3.8"
services:
        sql-server:
                container_name: sql-server
                image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
                expose:
                        - "1433"
                env_file:
                        - ./sql-server/scripts/.sql_secrets
                volumes:
                        - services_sqlvolume:/var/opt/mssql
                networks:
                        - servicenet

        bot:
                container_name: discord-bot
                build: 
                        context: .
                        dockerfile: Dockerfile
                image: discord-bot:beta
                expose:
                        - "1443"
#                volumes:
#                        - .:/usr/src/app
                networks:
                        - servicenet
                depends_on:
                        - test-server
volumes:
        services_sqlvolume:
                external: true

networks:
        servicenet:
                driver: bridge

